### ISSUE TITLE
SCSS scopes are missing

### ISSUE THREAD

**Issue by smlombardi** [pouyakary/ProColors#5]
I forked your theme and noticed the various colors applied to css and less files do not apply to scss files. For example:

```yaml
  - name: CSS property
    scope: property-name.css
    color: .green
```

I assume this should be

```yaml
  - name: CSS property
    scopes: 
      - property-name.css
      - property-name.scss
    color: .green
```

I'm happy to add these in a PR but I'm a bit confused by the theme generation process with themeX.  I installed the node package, and the test passes but I can't actually generate any editor themes.  I will read the docs and see if I can figure it out.  In the meantime, it would be great to add SCSS to the CSS and LESS defs.
